### ISSUE TITLE
Access protected routes via Paseto token

### ISSUE THREAD

**Issue by linatt** [mstaack/lumen-api-starter#12]
Hi there,

I would like to know how I can access the protected routes after loggin in with my  email and password. I do receive the token but when I post it to /auth/user I only get 401.

Best regards
linatt

**Comment by mstaack** [comment]
hi you need to specify an Authorization Header
check: https://github.com/mstaack/lumen-api-starter/blob/master/app/Extensions/Authentication/PasetoAuthGuard.php#L118
