### ISSUE TITLE
Upgrade to Lumen 5.7

### ISSUE THREAD

**Issue by stefanvanherwijnen** [mstaack/lumen-api-starter#18]
I think the only relevant change in code is the cache directory in the storage/framework folder
(https://laravel.com/docs/5.7/upgrade#upgrade-5.7.0)

**Comment by mstaack** [comment]
sure will do

**Comment by mstaack** [comment]
@stefanvanherwijnen mind doing a pr?

**Comment by stefanvanherwijnen** [comment]
I just did a PR.
I also updated laravel-permission because version 2.22 was broken.
