### ISSUE TITLE
Turn of user email verification

### ISSUE THREAD

**Issue by tanthammar** [mstaack/lumen-api-starter#27]
Sorry to bother you here ...
First time using Lumen, only used Laravel before.

The current setup requires the user to verify their email.

In Laravel I can remove the "Illuminate\Contracts\Auth\MustVerifyEmail" contract on the User Model, but I can't find it in this installation. Can you please direct me to where I can disable the email verification?

(Took me a while to figure out why the seeded demo@demo.com returned the email/password error")

**Comment by mstaack** [comment]
have a look at the `AuthController` and `User` Model

https://github.com/mstaack/lumen-api-starter/blob/master/app/User.php#L113

you could also change the migration to use `true` as default in:
https://github.com/mstaack/lumen-api-starter/blob/master/database/migrations/2018_03_03_232931_create_users_table.php#L20
