### ISSUE TITLE
Add option to refresh token

### ISSUE THREAD

**Issue by mstaack** [mstaack/lumen-api-starter#4]

**Comment by stefanvanherwijnen** [comment]
I have been looking quite a while for a good starter for a lumen API with authentication. Your repository was the best I could find, but it still lacks some features. My question is: what is your goal with this repo and are you planning on maintaining it? My idea is to create a simple and secure base for a lumen API and keep it up to date. I added email verification and the possibility to change the user's password, so if you want I could contribute here.

**Comment by mstaack** [comment]
hey @stefanvanherwijnen thanks, of course i will keep this up to date.
Would love to see some contributions.

cheers max

**Comment by stefanvanherwijnen** [comment]
Ok great.

With regards to this issue, I don't think paseto has a function to refresh the tokens, so what would be the best approach? Store a table with refresh tokens and see if the submitted refresh token matches the one in the table?

Edit:
I see this is actually already implemented in the users table:
$table->rememberToken();
